"""add target_days to deck

Revision ID: 2d484e53fc69
Revises: d55a8af2ce4f
Create Date: 2026-08-31 18:12:41.912047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d484e53fc69'
down_revision = 'd55a8af2ce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('target_days')

    # ### end Alembic commands ###
