"""add terms_per_day to deck

Revision ID: 5972278a6e56
Revises: 2d484e53fc69
Create Date: 2026-08-31 18:39:09.461456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5972278a6e56'
down_revision = '2d484e53fc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('terms_per_day')

    # ### end Alembic commands ###
